dist: bionic

language: go

go:
  - 1.16.x

env:
  global:
    - AWS_PROFILE=awsweeper
    - AWS_DEFAULT_REGION=us-west-2

before_install:
  - ./before_ci.sh

install:
  - make setup

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
